### ISSUE TITLE
GPU not found on docker

### ISSUE THREAD

**Issue by berkekisin** [tomdbar/ecord#1]
Hello,
as i tried to train a model, docker could not see my GPU. I solved this by adding "--gpus all" to docker run command. 
Instead of this docker run -itd --rm --name ecord_container -v /local/path/to/ecord/:/home/app/ecord ecord,
docker run -itd --gpus all  --rm --name ecord_container -v /local/path/to/ecord/:/home/app/ecord ecord.
It would be good to point out that in the readMe file.

**Comment by tomdbar** [comment]
Hi - thanks for flagging that up :).  Indeed it is a bit confusing to start the installation assuming a GPU is available but then neglect that when running the Docker image.  I'll update the README right now!
