### ISSUE TITLE
Validation bug

### ISSUE THREAD

**Issue by berkekisin** [tomdbar/ecord#3]
Hello,
i followed the exact steps as you described in readme file and got the following error. 

![Screenshot from 2022-06-18 16-21-48](https://user-images.githubusercontent.com/70319815/174442718-f6eac590-8749-4913-ab9a-4529efcb4579.png)

**Comment by tomdbar** [comment]
I can not reproduce this (see below).  From the error it looks like the saved model parameters are the wrong shape for the configured network(s) - have you made any changes to the code/scripts from the main branch?  Is this a fresh run on a new VM, or is there any chance of local changes having an effect?  In my case, a fresh set-up on a VM (with a GPU on GCP, so no changes to the provided Dockerfile) following the README gives me the below.

![Screenshot 2022-06-18 at 16 43 43](https://user-images.githubusercontent.com/41467971/174446076-88fb492c-970d-4ef1-a90e-4faa31ba70e2.png)

**Comment by berkekisin** [comment]
doing a fresh start solved the problem thanks :)
